require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpaappsController do

  # This should return the minimal set of attributes required to create a valid
  # Ipaapp. As you add validations to Ipaapp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpaappsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ipaapps as @ipaapps" do
      ipaapp = Ipaapp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ipaapps).should eq([ipaapp])
    end
  end

  describe "GET show" do
    it "assigns the requested ipaapp as @ipaapp" do
      ipaapp = Ipaapp.create! valid_attributes
      get :show, {:id => ipaapp.to_param}, valid_session
      assigns(:ipaapp).should eq(ipaapp)
    end
  end

  describe "GET new" do
    it "assigns a new ipaapp as @ipaapp" do
      get :new, {}, valid_session
      assigns(:ipaapp).should be_a_new(Ipaapp)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipaapp as @ipaapp" do
      ipaapp = Ipaapp.create! valid_attributes
      get :edit, {:id => ipaapp.to_param}, valid_session
      assigns(:ipaapp).should eq(ipaapp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ipaapp" do
        expect {
          post :create, {:ipaapp => valid_attributes}, valid_session
        }.to change(Ipaapp, :count).by(1)
      end

      it "assigns a newly created ipaapp as @ipaapp" do
        post :create, {:ipaapp => valid_attributes}, valid_session
        assigns(:ipaapp).should be_a(Ipaapp)
        assigns(:ipaapp).should be_persisted
      end

      it "redirects to the created ipaapp" do
        post :create, {:ipaapp => valid_attributes}, valid_session
        response.should redirect_to(Ipaapp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipaapp as @ipaapp" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaapp.any_instance.stub(:save).and_return(false)
        post :create, {:ipaapp => {  }}, valid_session
        assigns(:ipaapp).should be_a_new(Ipaapp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaapp.any_instance.stub(:save).and_return(false)
        post :create, {:ipaapp => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipaapp" do
        ipaapp = Ipaapp.create! valid_attributes
        # Assuming there are no other ipaapps in the database, this
        # specifies that the Ipaapp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ipaapp.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => ipaapp.to_param, :ipaapp => { "these" => "params" }}, valid_session
      end

      it "assigns the requested ipaapp as @ipaapp" do
        ipaapp = Ipaapp.create! valid_attributes
        put :update, {:id => ipaapp.to_param, :ipaapp => valid_attributes}, valid_session
        assigns(:ipaapp).should eq(ipaapp)
      end

      it "redirects to the ipaapp" do
        ipaapp = Ipaapp.create! valid_attributes
        put :update, {:id => ipaapp.to_param, :ipaapp => valid_attributes}, valid_session
        response.should redirect_to(ipaapp)
      end
    end

    describe "with invalid params" do
      it "assigns the ipaapp as @ipaapp" do
        ipaapp = Ipaapp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaapp.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipaapp.to_param, :ipaapp => {  }}, valid_session
        assigns(:ipaapp).should eq(ipaapp)
      end

      it "re-renders the 'edit' template" do
        ipaapp = Ipaapp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaapp.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipaapp.to_param, :ipaapp => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipaapp" do
      ipaapp = Ipaapp.create! valid_attributes
      expect {
        delete :destroy, {:id => ipaapp.to_param}, valid_session
      }.to change(Ipaapp, :count).by(-1)
    end

    it "redirects to the ipaapps list" do
      ipaapp = Ipaapp.create! valid_attributes
      delete :destroy, {:id => ipaapp.to_param}, valid_session
      response.should redirect_to(ipaapps_url)
    end
  end

end
